##                                    IMPORTING LIBRARIES

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# IMPORTING DATASETS

In [2]:
dataset = pd.read_csv('emails.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
X

array([["Subject: naturally irresistible your corporate identity  lt is really hard to recollect a company : the  market is full of suqgestions and the information isoverwhelminq ; but a good  catchy logo , stylish statlonery and outstanding website  will make the task much easier .  we do not promise that havinq ordered a iogo your  company will automaticaily become a world ieader : it isguite ciear that  without good products , effective business organization and practicable aim it  will be hotat nowadays market ; but we do promise that your marketing efforts  will become much more effective . here is the list of clear  benefits : creativeness : hand - made , original logos , specially done  to reflect your distinctive company image . convenience : logo and stationery  are provided in all formats ; easy - to - use content management system letsyou  change your website content and even its structure . promptness : you  will see logo drafts within three business days . affordability : 

IMPORTING DATASET CONTAINING SPAM WORDS.

In [23]:
spamdataset = pd.read_csv('spamwords.csv')
spam = spamdataset.iloc[:,-1].values
l=[]
for word in spam:
    l.append(word.lower())
            
l   

['act now',
 'buy',
 'call now',
 'click',
 'click below',
 'click here',
 'compare',
 'do it today',
 'don’t delete',
 'free',
 'get',
 'give it away',
 'open',
 'opt in',
 'order',
 'order now',
 'print from signature',
 'print out and fax',
 'see for yourself',
 'sign up free today',
 'stop',
 'unsubscribe',
 'visit our website',
 'congratulations',
 'giving away',
 'prize',
 'prizes',
 'talks about prizes',
 'who really wins?',
 'win',
 'winner',
 'won',
 'you are a winner!',
 'you have been selected',
 'you’re a winner!',
 'confidentially on all orders',
 'order today',
 'orders shipped by',
 'outstanding values',
 'sample',
 'wants credit card',
 'what are you waiting for?',
 '“hidden” assets',
 '$$$',
 'additional income',
 'apply online',
 'avoid bankruptcy',
 'be your own boss',
 'beneficiary',
 'big bucks',
 'billion',
 'billion dollars',
 'calling creditors',
 'cash',
 'cash bonus',
 'cashcashcash',
 'casino',
 'cents on the dollar',
 'check',
 'check or money order',
 'coll

## MAKING THE FINAL LIST TO WORK WITH LOGISTIC REGRESSION

In [5]:
l2=[]
for sentences in X:
    s = str(sentences)
    count = 0
    for spam in l:
        if spam in s:
            count = count+1
    l2.append(count/len(s))
l2 

[0.008736559139784945,
 0.0016611295681063123,
 0.017699115044247787,
 0.017857142857142856,
 0.016736401673640166,
 0.004149377593360996,
 0.0024583155194527577,
 0.017777777777777778,
 0.007827788649706457,
 0.017777777777777778,
 0.0070126227208976155,
 0.017777777777777778,
 0.015855039637599093,
 0.002559414990859232,
 0.010174418604651164,
 0.010945273631840797,
 0.0319634703196347,
 0.0074962518740629685,
 0.023809523809523808,
 0.01014040561622465,
 0.019830028328611898,
 0.016845329249617153,
 0.015299026425591099,
 0.016778523489932886,
 0.01977401129943503,
 0.010030090270812437,
 0.010638297872340425,
 0.00425531914893617,
 0.001996007984031936,
 0.017777777777777778,
 0.0297029702970297,
 0.00511585916340656,
 0.02247191011235955,
 0.0029390154298310064,
 0.004012036108324975,
 0.005738880918220947,
 0.014285714285714285,
 0.016574585635359115,
 0.00819672131147541,
 0.007276507276507277,
 0.018315018315018316,
 0.005291005291005291,
 0.0024554286324330096,
 0.007017543859

## SPLITTING  DATASET 


In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(l2, y, test_size = 0.25,random_state=1)

In [16]:
X_train = np.array(X_train)
X_train = X_train.reshape(len(X_train),1)
X_train

array([[0.01219512],
       [0.02298851],
       [0.00625   ],
       ...,
       [0.00582363],
       [0.00328407],
       [0.00495663]])

## RESHAPING X_TEST

In [17]:
X_test = np.array(X_test)
X_test = X_test.reshape(len(X_test),1)
X_test

array([[0.003861  ],
       [0.00181488],
       [0.00288018],
       ...,
       [0.00519931],
       [0.01041667],
       [0.00099174]])

## APPLYING FEATURE SCALING

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## APPLYING LOGISTIC REGRESSION MODEL


In [19]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state =1)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=1, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## PREDICTING THE TEST RESULTS

In [20]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 1]
 [0 0]]


## CHECKING THE ACCURACY OF THE MODEL


In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1030   53]
 [ 213  136]]


0.8142458100558659